---
title: "4 Semester Flashbacks"
author: "MP"
date: "2025-05-05"
output: html_document
---


```{r}
library(readr)
library(dplyr)
library(tibble)
```


```{r}
url <- "https://hub.dkfz.de/s/tw4GYqYC9MFfG3p/download/RDeeP_HeLa_NS.csv.zip"

#Create a temporary file and download the ZIP
temp_file <- tempfile()
download.file(url, temp_file)
zip_contents <- unzip(temp_file, list = TRUE)
print(zip_contents)

csv_file <- unzip(temp_file, files = zip_contents$Name[1], exdir = tempdir())
Hela_NS <- read.csv(csv_file, sep = ";")
Hela_NS <- Hela_NS %>%
  column_to_rownames("Protein_Name")
```

#How to histogram (distrubution of the variable)
Q: how are proteins amounts distributed in each fraction?
```{r}
hist(Hela_NS$Fraction1_Ctrl_Rep1, 
     main = "Protein Distribution in Fraction1_Ctrl_Rep1", 
     xlab = "Protein Amount", 
     col = "skyblue", 
     breaks = 30)
```
#For better visualization
```{r}
hist(log10(Hela_NS$Fraction1_Ctrl_Rep1 + 1),
     main = "Log10 Protein Abundance",
     xlab = "log10 Protein Amount",
     col = "skyblue",
     breaks = 30)
```
#Finding a good plot
```{r}
# Find the maximum value in the whole dataset
max_value <- max(Hela_NS, na.rm = TRUE)

# Or more directly: which column contains the max value
column_with_max <- names(which(sapply(Hela_NS, function(col) any(col == max_value, na.rm = TRUE))))

# Also get the protein name (row) where it occurs
protein_with_max <- rownames(Hela_NS)[which(Hela_NS[[column_with_max]] == max_value)]

# Output
cat("Column with highest abundance:", column_with_max, "\n")
cat("Protein with highest abundance:", protein_with_max, "\n")
cat("Max value:", max_value, "\n")

```

```{r}
hist(log10(Hela_NS$Fraction8_RNase_Rep2 + 1),
     main = "Log10 Protein Abundance",
     xlab = "log10 Protein Amount",
     col = "skyblue",
     breaks = 30)
```


